### ISSUE TITLE
Problem when using the filter with a file with yaml header

### ISSUE THREAD

**Issue by beingalink** [NMarkgraf/typography.py#4]
Not sure if actually related to the yaml header but this is what I'm trying to do:

Input file:
```
---
documentclass: article
geometry: a4paper, landscape, margin=2cm
lang: de-DE
header-includes:
    - \usepackage{xspace}
---
Das ist ein Test, um u.a. festzustellen,
wie z.B. deutsche Typografie aussieht.
```
Used pandoc command:
```
pandoc -i input.md -o output.pdf --pdf-engine=xelatex --filter='typography.py'
```
The pandoc error message:
```
Error producing PDF.
! Undefined control sequence.
\reserved@b ...x {margin=2\thinspace {}cm}\xspace 
                                                  {}}][{}]\noexpand \@pkgext...
l.44 \setlength

Der Terminalprozess wurde mit folgendem Exitcode beendet: 43
```
When I remove "margin=2cm" from the geometry part, the pandoc conversion works fine. Not sure what the problem is.

Thanks in advance for any help!

**Comment by NMarkgraf** [comment]
Oh, I see! 

The mistake is easy to see, but I guess it takes until next weekend to fix it. 
Currently, the filter runs through all the markdown file, even the YAML block in the beginning. It replaces "2cm" by "2\thinspace{}cm" which is not a correct length for LaTeX. 
The filter should not run through a YAML block, I guess. The short workaround would be to calc the pt of 2cm by hand (which is nearly 56.6929pt) and use "margin=56.6920pt" instead of "margin=2cm". 
But I guess, after the Easter holidays I will fix this bug. 

Thank you Tobias!

**Comment by beingalink** [comment]
Oh, that was quick. Thanks for your response. I have no idea about the inner workings of pandoc and its filters but I thought filters work on some json representation of the source file so I was a bit surprised by the diagnosis result. Seems like filter authors have to handle more things than I was aware of.

Thanks for fixing the problem and enjoy your Easter holidays!

**Comment by NMarkgraf** [comment]
I knew it took longer than expected. But finally, I got it!

**Comment by beingalink** [comment]
Great! It seems to work fine now. In the readme the sentence `Für LaTeX muss das Paket xspace (durch ein passendes \usepackage{xspace}) geladen sein.` doesn't seem to be necessary anymore as packages seem to be auto-added by the filter (they only need to be present in the tex distribution).
